ypro/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login, name='login'),
  path('logout/',views.logout, name='logout'),
  path('list/liga', views.LigaBoardList.as_view(), name='list_liga'),
  path('list/premier', views.PremierBoardList.as_view(), name='list_premier'),
  path('list/serie', views.SerieBoardList.as_view(), name='list_serie'),
  path('list/bundes', views.BundesBoardList.as_view(), name='list_bundes'),
  path('list/liegue', views.LigueBoardList.as_view(), name='list_ligue'),
  path('detail/<int:pk>', views.BoardDetail.as_view(), name='detail'),
  path('update/<int:pk>', views.BoardUpdate.as_view(), name='update'),
  path('create/', views.BoardCreate.as_view(), name='create'),
  path('delete/<int:pk>', views.BoardDelete.as_view(), name='delete'),
]

ypro/ypro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += staticfiles_urlpatterns()
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

ypro/board/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not username:#
            raise ValueError('Users must have an name')
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)#normalize_emailは正規表現化
        username = self.model.normalize_username(username)


        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):#
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)#

    def create_superuser(self, username, email, password, **extra_fields):#
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username ,email, password, **extra_fields)#


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    username = models.CharField(_('username'), max_length=30, unique=True)#
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']#nameを入れないとcreatesuperuserで作成できない

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


###########################################################################


class Nation(models.Model):
  name = models.CharField(max_length=100, unique=True)
  def __str__(self):
    return self.name

class Club(models.Model):
  name = models.CharField(max_length=100, unique=True)
  nation = models.ForeignKey('Nation', related_name='club', on_delete=models.PROTECT)
  def __str__(self):
    return self.name

positions = (
    ('FW','FW'),
    ('MF','MF'),
    ('DF','DF')
)

leagues = (
  ('Premier', 'Premier'),
  ('Liga', 'Liga'),
  ('Serie A', 'Serie A'),
  ('Bundes', 'Bundes'),
  ('Ligue 1', 'Ligue 1'),
)

class Player(models.Model):
  name = models.CharField(max_length=50)

  nation = models.ForeignKey('Nation',related_name='player',on_delete=models.PROTECT)

  age = models.IntegerField()

  league = models.CharField(max_length=50, choices=leagues,default='Liga')

  club = models.ForeignKey('Club',related_name='player', on_delete=models.PROTECT, default='Barcelona')

  position = models.CharField(max_length=30, choices=positions)

  image = models.ImageField(upload_to='playerImages/', null=True, blank=True)

  # image_thumbnail = ImageSpecField(
  #   source='image',
  #   processors=[ResizeToFill(100,100)],
  #   format='JPEG',
  #   options={'quality': 60}
  # )

  feature = models.TextField(max_length=400, null=True, blank=True)

  def __str__(self):
    return self.name

ypro/board/views.py
from .models import Player, Nation, Club
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import login as dj_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

# Create your views here.
def signup(request):
  if request.method == 'POST':
    input_username = request.POST['username']
    input_email = request.POST['email']
    input_password = request.POST['password']

    try:
      User.objects.filter(username=input_username,password=input_password)
      return render(request, 'board/signup.html', {'message':'These username,emailaddress has already been used.'})
    except:
      User.objects.create_user(input_username, input_email, input_password)
      return render(request, 'board/signup.html', {'message':'complete!!!'})

  return render(request, 'board/signup.html', {'message': 'Please make your accounts!'})

def login(request):
  if request.method == 'POST':
    input_username = request.POST['username']
    input_password = request.POST['password']
    input_email = request.POST['email']

    user = authenticate(username=input_username, email=input_email, password=input_password)

    if user is not None:
      dj_login(request, user)
      return redirect('board:list_liga')
    else:
      return render(request, 'board/signup.html')

  return render(request, 'board/login.html')

def logout(request):
  logout(request)
  return redirect('login')



class LigaBoardList(ListView):
  template_name = 'board/list.html'
  model = Player
  queryset = Player.objects.filter(league='Liga')
  context_object_name = 'player_list'
  def get_context_data(self, **kwargs):
    params = super(LigaBoardList, self).get_context_data(**kwargs)
    params['league'] = 'Liga Española'
    return params


  # paginate_by = 3

  # 他モデル参照方法
  # def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        # context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        # context['book_list'] = Book.objects.all()
        # return context
  # dataを軽くする foreignkey不可
  # def get_queryset(self):
  #   qs = self.model.objects.prefetch_related(Player)
  #   return qs

class PremierBoardList(ListView):
  template_name = 'board/list.html'
  model = Player
  context_object_name = 'player_list'
  queryset = Player.objects.filter(league='Premier')



class SerieBoardList(ListView):
  template_name = 'board/list.html'
  model = Player
  context_object_name = 'player_list'
  queryset = Player.objects.filter(league='Serie A')



class BundesBoardList(ListView):
  template_name = 'board/list.html'
  model = Player
  context_object_name = 'player_list'
  queryset = Player.objects.filter(league='Bundes')



class LigueBoardList(ListView):
  template_name = 'board/list.html'
  model = Player
  context_object_name = 'player_list'
  queryset = Player.objects.filter(league='Ligue 1')



class BoardDetail(DetailView):
  template_name = 'board/detail.html'
  model = Player
  context_object_name = 'player'
  # login_url = '/login/'



class BoardUpdate(UpdateView):
  template_name = 'board/update.html'
  model = Player
  fields = ('name', 'age', 'league', 'club', 'position', 'feature')
  success_url = reverse_lazy('board:list_liga')
  context_object_name = 'player'



class BoardCreate(CreateView):
  template_name = 'board/create.html'
  model = Player
  fields = ('name', 'age', 'league', 'club', 'position', 'image', 'feature')
  success_url = reverse_lazy('board:list_liga')
  context_object_name = 'player'



class BoardDelete(DeleteView):
  template_name = 'board/delete.html'
  model = Player
  success_url = reverse_lazy('board:list_liga')

ypro/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BucciaraTimes</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'board/css/base.css' %}">

  {% block customcss %}

  {% endblock customcss %}
</head>
<body>
  <div class="bg">

    <header>

      <svg class="bi bi-dash-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
        <path fill-rule="evenodd" d="M3.5 8a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.5-.5z"/>
      </svg>
      <div class="container">
        <div class="title-wrapper">

          <h1>BucciaraTimes</h1>
          <h4>Please Tell Me Your Evaluation Of That Player, Manager, Team, and Transfer.</h4>

        </div>
      </div>
    </header>

  {% block contents %}

  {% endblock contents %}


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="board/js/main.js"></script>
  </div>
  </body>
</html>

ypro/templates/board/create.html
{% extends 'board/base.html' %}
{% load static %}

{% block customcss %}
  <link rel="stylesheet" href="{% static 'board/css/main.css' %}">
{% endblock customcss %}

{% block contents %}

<div class="panel">
  <form action="" method="POST">
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Create">
  </form>
</div>

{% endblock contents %}

ypro/templates/board/delete.html
{% extends 'board/base.html' %}
{% load static %}

{% block customcss %}
 <link rel="stylesheet" href="{% static 'board/css/sub.css' %}">
  <link rel="stylesheet" href="{% static 'board/css/main.css' %}">
{% endblock customcss %}

{% block contents %}

<div class="panel">
  {{form.as_p}}
  <form action="" method="POST">
    {% csrf_token %}

    <input type="submit" value="Delete">
  </form>
</div>

{% endblock contents %}

ypro/templates/board/detail.html
{% extends 'board/base.html' %}
{% load static %}

{% block customcss %}
  <link rel="stylesheet" href="{% static 'board/css/main.css' %}">
{% endblock customcss %}

{% block contents %}

<div class="panel">
  <h5 class="name">{{ player.name }}</h5>
  <ul class="itemlist">
    {% if player.image %}
    <div class="img">
      <li class="img"><img src="{{ player.image.url }}"></li>
    </div>
    {% endif %}
    <div class="info">
      <li class="age">{{ player.age }}</li>
      <li class="club">{{ player.club }}</li>
      <li class="nation">{{player.nation }}</li>
    </div>
  </ul>
</div>

{% endblock contents %}

ypro/templates/board/list.html
{% extends 'board/base.html' %}
{% load static %}
 {% block customcss %}
  <link rel="stylesheet" href="{% static 'board/css/list.css' %}">
 {% endblock customcss %}
<body>
  {% block contents %}

  <main class="directory">
    <div class="container">
      <h3 class="title">Players List</h3>

      <nav>

        <ul class="league">
          <li class="btn btn-outline-warning liga"><a href="{% url 'board:list_liga' %}" >Liga</a></li>
          <li class="btn btn-outline-primary premier"><a href="{% url 'board:list_premier' %}" >Premier</a></li>
          <li class="btn btn-outline-success serie"><a href="{% url 'board:list_serie' %}" >SerieA</a></li>
          <li class="btn btn-outline-danger bundes"><a href="{% url 'board:list_bundes' %}" >Bundes</a></li>
          <li class="btn btn-outline-info ligue"><a href="{% url 'board:list_ligue' %}" >Ligue1</a></li>
        </ul>

      </nav>
      
      <h4 class="subtitle">{{ league }}</h4>

      <div class="grid">

        {% for player in player_list %}
        <div class="panel">
        <h5 class="name"><a href="{% url 'board:detail' player.pk %}">{{ player.name }}</a></h5>
        <ul class="itemlist">
          <!-- {% if player.image %}
          <div class="img">
            <li><img src="{{ player.image.url }}" width="100" height="100"></li>
          </div>
          {% endif %} -->
          <div class="info">
            <li class="nation">{{player.nation }}</li>
            <li class="club">{{ player.club }}</li>
            <li class="age">{{ player.age }}</li>
            <li class="position">{{ player.position }}</li>
            <li><a href="{% url 'board:update' player.pk %}">更新</a></li>
          </div>
        </ul>
      </div>
      {% endfor %}



    </div>
<!-- <a href="{% url 'board:logout' %}">logout</a> -->
  </div>
  </main>

  {% endblock contents %}
</body>
</html>

ypro/templates/board/login.html
{% extends 'board/base.html' %}
{% load static %}

{% block customcss %}
  <!-- <link rel="stylesheet" href="{% static 'board/css/main.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static 'board/css/sub.css' %}"> -->
  <link rel="stylesheet" href="{% static 'board/css/boot.css' %}">
{% endblock customcss %}

{% block contents %}

<body class="text-center">
  <form class="form-signin" method="POST" action="">{% csrf_token %}
<img class="mb-4" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
<h1 class="h3 mb-3 font-weight-normal">Please LOgin</h1>
<label for="inputEmail" class="sr-only">Username</label>
<input name='username' type="username" id="inputUsername" class="form-control" placeholder="username address" required autofocus>
<label for="inputEmail" class="sr-only">Email address</label>
<input name='email' type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
<label for="inputPassword" class="sr-only">Password</label>
<input name='password' type="password" id="inputPassword" class="form-control" placeholder="Password" required>
<div class="checkbox mb-3">
  <label>
    <input type="checkbox" value="remember-me"> Remember me
  </label>
</div>
<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
<p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>
</body>

{% endblock contents %}

ypro/templates/board/signup.html
{% extends 'board/base.html' %}
{% load static %}

{% block customcss %}
  <!-- <link rel="stylesheet" href="{% static 'board/css/main.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static 'board/css/sub.css' %}"> -->
  <link rel="stylesheet" href="{% static 'board/css/boot.css' %}">
{% endblock customcss %}

{% block contents %}

<body class="text-center">
  <form class="form-signin" method="POST" action="">{% csrf_token %}
<img class="mb-4" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
<label for="inputEmail" class="sr-only">Email address</label>
<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name='email'>
<label for="inputPassword" class="sr-only">Password</label>
<input type="password" id="inputPassword" class="form-control" placeholder="Password" required name='password'>
<div class="checkbox mb-3">
  <label>
    <input type="checkbox" value="remember-me"> Remember me
  </label>
</div>
<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
<p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>
</body>

{% endblock contents %}

ypro/templates/board/update.html
{% extends 'board/base.html' %}
{% load static %}

{% block customcss %}
  <link rel="stylesheet" href="{% static 'board/css/main.css' %}">
{% endblock customcss %}

{% block contents %}

<div class="panel">
  <form action="" method="POST">
    {% csrf_token %}

       {{ form.name }}
       {{ form.age }}
       {{ form.league }}
       {{ form.club }}
       {{ form.position }}
       {{ form.feature }}

    <input type="submit" value="Update">
  </form>
</div>

{% endblock contents %}